# Created using wingetcreate 1.6.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: DoltHub.Dolt
PackageVersion: 1.43.5
InstallerLocale: en-US
Platform:
- Windows.Desktop
InstallerType: wix
Scope: machine
UpgradeBehavior: install
ProductCode: '{0733F2B9-48A6-4E88-98C6-84D556CCD7C4}'
AppsAndFeaturesEntries:
- DisplayName: Dolt 1.42.20
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/dolthub/dolt/releases/download/v1.43.5/dolt-windows-amd64.msi
  InstallerSha256: 67F26FED523B44D5C4D4F8FEC092126E2AA098FD3FE29568006A86DFC3C39577
ManifestType: installer
ManifestVersion: 1.6.0
ReleaseDate: 2024-10-12
