# Created using wingetcreate 1.0.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: DoltHub.Dolt
PackageVersion: 0.40.1
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
Scope: machine
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerType: wix
  InstallerUrl: https://github.com/dolthub/dolt/releases/download/v0.40.1/dolt-windows-amd64.msi
  InstallerSha256: 2939CAFB46FC2C532E3B880C64B3AAAA43A130F5CE817452B3DBB2D3FF924D87
  ProductCode: '{8A57FA34-3075-4DB0-BC0E-083C8DC88C57}'
ManifestType: installer
ManifestVersion: 1.1.0

